name: "goltz20707 blog"
description: "Just some random blog."
url: https://goltz20707.mmert.org
enforce_ssl: goltz20707.mmert.org

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
