name: "goltz20707 blog"
description: "Just some random blog."
url: /foo/bar

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
